include $(THEOS)/makefiles/common.mk

TWEAK_NAME = @@PROJECTNAME@@

$(TWEAK_NAME)_FILES = Tweak.xm

$(TWEAK_NAME)_CFLAGS = -fobjc-arc
$(TWEAK_NAME)_LDFLAGS += r16Menu/libr16Menu.dylib

include $(THEOS_MAKE_PATH)/tweak.mk
